# Generated by Django 3.2.4 on 2021-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20210710_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
